### ISSUE TITLE
Problem with preparation of chainfiles when the number of scaffold is high

### ISSUE THREAD

**Issue by everestial** [churchill-lab/g2gtools#7]
I have realized that when the number of scaffold is high, the chain file have some inconsistencies.

As, a test, I ran vcf2chain with vcf that has data only for chr_2, but with genome that have 10 major curated chromosome and several other  uncurated scaffolds. It is supposed to prepare chain coordinates only for chr2 but instead it prepares the chain files for several other scaffolds. When I reduced the number of chromosome, the chain file was prepared only for one chromosome. Any tips on the issue?

**Comment by rishavray** [comment]
I think I figured out the issue. It has to do with the shallow copy of the lists in vcf2chain.py. I got it working by deep copying the data structures for every chromosome and scaffold. Due to the shallow copy, any changes made for one chromosome gets reflected in the others as well. However, when the multiprocessor is enabled, this does not happen always when there is a fewer number of chromosomes. I did not test my code extensively in all Python versions, hence I am bit skeptical issuing a pull request as of now. If you need a quick fix, I can paste the code.
